{
    "name": 'Custom POS order number || POS Customised Receipt Order number',
    "version":"13.1.1.1",    
    "sequence": 1,
    "summary": 'Customised POS Receipt Order number',
    "description": """ Customised POS Receipt Order number """,    
    "category": 'Point of Sale',    
    "author" : "MAISOLUTIONSLLC",
    "email": 'apps@maisolutionsllc.com',
    "website":'http://maisolutionsllc.com/',
    "license": 'OPL-1', 
    'depends' : ['point_of_sale'],      
    "price": 14,
    "currency": "EUR",    
    'data': [
        'views/pos_config.xml',
        'views/templates.xml',
    ],
    "live_test_url" : " https://youtu.be/CcL_NqRWhjY ", 
    "qweb": [],
    "test": [],
    "installable": True,
    "application": False,
    "auto_install": False,
    "images": ['static/description/main_screenshot.png'],
}

